### ISSUE TITLE
Feature set of the CLI plugin

### ISSUE THREAD

**Issue by Jeeppler** [checkmarx-ltd/CLI#103]
What are the features/actions I can execute with this CLI plugin? Can I do everything which I can do with [REST API](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/3084883007/CxSAST+v9.4+REST+API)?

**Comment by jbrotsos** [comment]
No, this is definitely limited.  Here is the documentation:

https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1339424904/CLI+Plugin
